/**
 * ERP Manajemen - Granular Permission Catalog & Role Mappings
 */

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: "dashboard.view",

  // Master Data & Company
  COMPANY_VIEW: "company.view",
  COMPANY_MANAGE: "company.manage",

  // Inventory & Warehouse
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_MANAGE: "inventory.manage",

  // Purchasing
  PURCHASING_VIEW: "purchasing.view",
  PURCHASING_MANAGE: "purchasing.manage",

  // Sales
  SALES_VIEW: "sales.view",
  SALES_MANAGE: "sales.manage",

  // Finance
  FINANCE_VIEW: "finance.view",
  FINANCE_MANAGE: "finance.manage",

  // Accounting
  ACCOUNTING_VIEW: "accounting.view",
  ACCOUNTING_MANAGE: "accounting.manage",

  // Assets
  ASSET_VIEW: "asset.view",
  ASSET_MANAGE: "asset.manage",

  // Intercompany
  INTERCOMPANY_VIEW: "intercompany.view",
  INTERCOMPANY_MANAGE: "intercompany.manage",

  // Reporting
  REPORTS_VIEW: "reports.view",

  // Audit & Administration
  AUDIT_VIEW: "audit.view",
  USERS_MANAGE: "users.manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Standard Role to Permissions Mapping Matrix
 */
export const ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_MANAGE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_MANAGE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.INTERCOMPANY_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.USERS_MANAGE,
  ],
  OWNER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_MANAGE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_MANAGE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.INTERCOMPANY_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  DIRECTOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_MANAGE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_MANAGE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  COMPANY_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_MANAGE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_MANAGE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  FINANCE_MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.INTERCOMPANY_MANAGE,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
  ],
  FINANCE: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
  ],
  WAREHOUSE_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
  ],
  WAREHOUSE: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
  ],
  PURCHASING: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.FINANCE_VIEW,
  ],
  SALES: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.FINANCE_VIEW,
  ],
  AUDITOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  VIEWER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.INTERCOMPANY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
};
